on:
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

name: 'Main Branch'

jobs:
  test:
    name: 'Test'

    uses: ./.github/workflows/part_test.yml

  publish:
    name: 'Publish'

    uses: ./.github/workflows/part_publish.yml
    secrets:
      EXPO_TOKEN: '${{ secrets.EXPO_TOKEN }}'
